name: automerge
on:
  pull_request:
    types:
      - opened
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Merge
        run: |
          git config user.email ${GITHUB_ACTOR}@users.noreply.github.com
          git config user.name ${GITHUB_ACTOR}
          git pull ${{ github.event.pull_request.head.repo.clone_url }} ${{ github.event.pull_request.head.ref }}

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
